### ISSUE TITLE
更新13.0系统之后 系统小组件提示 Failed open script

### ISSUE THREAD

**Issue by io-oss** [scriptwidget/scriptwidget.github.io#2]
<img width="200" alt="截屏2022-10-28 01 25 42" src="https://user-images.githubusercontent.com/25923473/198357837-676d0388-a116-419d-8806-c899d9996318.png">

**Comment by everettjf** [comment]
13.0？还是16.0？
16.0 应该修复了

**Comment by io-oss** [comment]
> 13.0？还是16.0？ 16.0 应该修复了
@everettjf MacOS Ventura 13.0

**Comment by everettjf** [comment]
这个不是新版本啊。删除重新安装一下试试。
iOS版本是多少？
________________________________

**Comment by io-oss** [comment]
> 这个不是新版本啊。删除重新安装一下试试。 iOS版本是多少？

App Store里没有检测到更新，这个是系统信息

<img width="283" alt="图像" src="https://user-images.githubusercontent.com/25923473/199028689-f69faf05-5729-4927-bc9b-87bfd4b61438.png">
